language: php
services:
- mysql
php:
- 7.2
before_script:
- composer self-update --1
- composer install --prefer-source --no-interaction --dev
- php artisan testing-setup --username="root"
script: vendor/bin/phpunit
matrix:
  allow_failures:
  - php: 5.5
  fast_finish: true
notifications:
  on_success: always
  on_failure: always